<a href="https://colab.research.google.com/github/mokshana4/Models-Data-Science-Lab/blob/main/MDS_WEEK_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np

## 1. Indexing and Slicing NumPy Arrays

In [33]:
# Create a 1D array
arr_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original 1D array:", arr_1d)

# Indexing single elements
print("Element at index 3:", arr_1d[3])
print("Element at last index:", arr_1d[-1])

# Slicing (start:stop:step)
print("Elements from index 2 to 6 (exclusive):")
print(arr_1d[2:6])

print("Elements from the beginning to index 5 (exclusive):")
print(arr_1d[:5])

print("Elements from index 5 to the end:")
print(arr_1d[5:])

print("Every second element:")
print(arr_1d[::2])

print("Reversed array:")
print(arr_1d[::-1])


Original 1D array: [0 1 2 3 4 5 6 7 8 9]
Element at index 3: 3
Element at last index: 9
Elements from index 2 to 6 (exclusive):
[2 3 4 5]
Elements from the beginning to index 5 (exclusive):
[0 1 2 3 4]
Elements from index 5 to the end:
[5 6 7 8 9]
Every second element:
[0 2 4 6 8]
Reversed array:
[9 8 7 6 5 4 3 2 1 0]


In [34]:
# Create a 2D array
arr_2d = np.array([
    [10, 11, 12, 13],
    [14, 15, 16, 17],
    [18, 19, 20, 21]
])
print("\nOriginal 2D array:\n", arr_2d)

# Indexing a single element in 2D array (row, column)
print("Element at (row 1, col 2):", arr_2d[1, 2])

# Slicing rows and columns
print("First row:", arr_2d[0, :])
print("Second column:\n", arr_2d[:, 1])
print("Sub-array (first two rows, last two columns):\n", arr_2d[:2, 2:])

# Boolean indexing
print("Elements greater than 15:\n", arr_2d[arr_2d > 15])


Original 2D array:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Element at (row 1, col 2): 16
First row: [10 11 12 13]
Second column:
 [11 15 19]
Sub-array (first two rows, last two columns):
 [[12 13]
 [16 17]]
Elements greater than 15:
 [16 17 18 19 20 21]


## 2. Reshaping NumPy Arrays

In [35]:
# Create a 1D array with 12 elements
arr = np.arange(12)
print("Original 1D array:", arr)

# Reshape to a 3x4 2D array
arr_reshaped_3x4 = arr.reshape(3, 4)
print("\nReshaped to 3x4:\n", arr_reshaped_3x4)

# Reshape to a 4x3 2D array
arr_reshaped_4x3 = arr.reshape(4, 3)
print("\nReshaped to 4x3:\n", arr_reshaped_4x3)

# Reshape to a 2x2x3 3D array
arr_reshaped_3d = arr.reshape(2, 2, 3)
print("\nReshaped to 2x2x3:\n", arr_reshaped_3d)

# Using -1 to automatically determine one dimension
arr_auto_reshape = arr.reshape(3, -1)
print("\nReshaped to 3 rows (auto columns):\n", arr_auto_reshape)


Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to 4x3:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Reshaped to 2x2x3:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

Reshaped to 3 rows (auto columns):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [36]:
# Flatten an array (convert back to 1D)
flattened_arr_ravel = arr_reshaped_3x4.ravel()
print("\nFlattened array (ravel):", flattened_arr_ravel)

flattened_arr_flatten = arr_reshaped_3x4.flatten()
print("Flattened array (flatten):", flattened_arr_flatten)

# Add a new axis to an array
arr_new_axis_row = arr_1d[np.newaxis, :]
print("\n1D array with new axis (row vector):\n", arr_new_axis_row)
print("Shape:", arr_new_axis_row.shape)

arr_new_axis_col = arr_1d[:, np.newaxis]
print("\n1D array with new axis (column vector):\n", arr_new_axis_col)
print("Shape:", arr_new_axis_col.shape)


Flattened array (ravel): [ 0  1  2  3  4  5  6  7  8  9 10 11]
Flattened array (flatten): [ 0  1  2  3  4  5  6  7  8  9 10 11]

1D array with new axis (row vector):
 [[0 1 2 3 4 5 6 7 8 9]]
Shape: (1, 10)

1D array with new axis (column vector):
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Shape: (10, 1)


## 5. Understanding `np.stack()`

In [37]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Array a:", a)
print("Shape of a:", a.shape)
print("Array b:", b)
print("Shape of b:", b.shape)

# Stack along a new axis (default is axis=0)
stacked_array_default = np.stack((a, b))
print("\nStacked array (default axis=0):\n", stacked_array_default)
print("Shape of stacked_array_default:", stacked_array_default.shape)

# Stack along axis 1
stacked_array_axis1 = np.stack((a, b), axis=1)
print("\nStacked array (axis=1):\n", stacked_array_axis1)
print("Shape of stacked_array_axis1:", stacked_array_axis1.shape)



Array a: [1 2 3]
Shape of a: (3,)
Array b: [4 5 6]
Shape of b: (3,)

Stacked array (default axis=0):
 [[1 2 3]
 [4 5 6]]
Shape of stacked_array_default: (2, 3)

Stacked array (axis=1):
 [[1 4]
 [2 5]
 [3 6]]
Shape of stacked_array_axis1: (3, 2)


In [38]:
# Example with 2D arrays
arr_2d_1 = np.array([[1, 1], [2, 2]])
arr_2d_2 = np.array([[3, 3], [4, 4]])

print("\n2D Array 1:\n", arr_2d_1)
print("2D Array 2:\n", arr_2d_2)

stacked_2d_default = np.stack((arr_2d_1, arr_2d_2))
print("\nStacked 2D arrays (default axis=0):\n", stacked_2d_default)
print("Shape of stacked_2d_default:", stacked_2d_default.shape)

stacked_2d_axis1 = np.stack((arr_2d_1, arr_2d_2), axis=1)
print("\nStacked 2D arrays (axis=1):\n", stacked_2d_axis1)
print("Shape of stacked_2d_axis1:", stacked_2d_axis1.shape)

stacked_2d_axis2 = np.stack((arr_2d_1, arr_2d_2), axis=2)
print("\nStacked 2D arrays (axis=2):\n", stacked_2d_axis2)
print("Shape of stacked_2d_axis2:", stacked_2d_axis2.shape)


2D Array 1:
 [[1 1]
 [2 2]]
2D Array 2:
 [[3 3]
 [4 4]]

Stacked 2D arrays (default axis=0):
 [[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]]
Shape of stacked_2d_default: (2, 2, 2)

Stacked 2D arrays (axis=1):
 [[[1 1]
  [3 3]]

 [[2 2]
  [4 4]]]
Shape of stacked_2d_axis1: (2, 2, 2)

Stacked 2D arrays (axis=2):
 [[[1 3]
  [1 3]]

 [[2 4]
  [2 4]]]
Shape of stacked_2d_axis2: (2, 2, 2)


## 3. Joining NumPy Arrays

In [39]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

# Concatenate along axis 0 (rows)
concat_rows = np.concatenate((arr1, arr2), axis=0)
print("\nConcatenated along axis 0 (rows):\n", concat_rows)

# Concatenate along axis 1 (columns)
concat_cols = np.concatenate((arr1, arr2), axis=1)
print("\nConcatenated along axis 1 (columns):\n", concat_cols)


Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]

Concatenated along axis 0 (rows):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along axis 1 (columns):
 [[1 2 5 6]
 [3 4 7 8]]


In [40]:
# Vertical stacking (vstack) - equivalent to concatenate(axis=0) for 2D arrays
v_stack = np.vstack((arr1, arr2))
print("\nVertical Stack (vstack):\n", v_stack)

# Horizontal stacking (hstack) - equivalent to concatenate(axis=1) for 2D arrays
h_stack = np.hstack((arr1, arr2))
print("\nHorizontal Stack (hstack):\n", h_stack)



Vertical Stack (vstack):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack (hstack):
 [[1 2 5 6]
 [3 4 7 8]]


## 4. Splitting NumPy Arrays

In [41]:
arr_to_split = np.arange(16).reshape(4, 4)
print("Original array to split:\n", arr_to_split)

# Split into 2 equal sub-arrays horizontally (along rows)
h_split = np.hsplit(arr_to_split, 2)
print("\nHorizontal Split into 2 equal parts:\n", h_split)

# Split into 4 equal sub-arrays vertically (along columns)
v_split = np.vsplit(arr_to_split, 4)
print("\nVertical Split into 4 equal parts:\n", v_split)


Original array to split:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Horizontal Split into 2 equal parts:
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]

Vertical Split into 4 equal parts:
 [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [42]:
# Split using array_split (allows unequal splits or non-divisible splits)

# Split into 3 parts along axis 0 (rows)
split_axis0 = np.array_split(arr_to_split, 3, axis=0)
print("\nArray Split into 3 parts along axis 0 (rows):\n", split_axis0)

# Split into 3 parts along axis 1 (columns)
split_axis1 = np.array_split(arr_to_split, 3, axis=1)
print("\nArray Split into 3 parts along axis 1 (columns):\n", split_axis1)



Array Split into 3 parts along axis 0 (rows):
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]

Array Split into 3 parts along axis 1 (columns):
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [43]:
# Using split directly (requires equal division)
arr_1d_split = np.arange(10)
print("\nOriginal 1D array for split:", arr_1d_split)
split_1d = np.split(arr_1d_split, [3, 7]) # Split before index 3 and before index 7
print("Split 1D array at indices [3, 7]:", split_1d)


Original 1D array for split: [0 1 2 3 4 5 6 7 8 9]
Split 1D array at indices [3, 7]: [array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]
