<a href="https://colab.research.google.com/github/mokshana4/Models-Data-Science-Lab/blob/main/MDS_WEEK_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [2]:
import numpy as np
print(np.__version__)

2.0.2


### Comparing Python Lists and NumPy Arrays Performance

This section demonstrates the performance differences between standard Python lists and NumPy arrays for common operations, especially with large datasets.

As you can see from the output, NumPy arrays are significantly faster for numerical operations, especially with large datasets, due to their optimized C implementations. This is why NumPy is preferred for scientific computing and data analysis in Python.

### Memory Usage Comparison

Let's compare the memory footprint of Python lists versus NumPy arrays for storing numerical data.

As shown above, NumPy arrays are significantly more memory-efficient for numerical data than Python lists. This is because Python lists store actual Python objects (which have their own overhead) and only store references to these objects, while NumPy arrays store raw data in a contiguous block of memory.

In [5]:
import sys
import numpy as np

# Number of elements for comparison
num_elements = 100000

print(f"Comparing memory usage for {num_elements} elements:")

# --- Python List Memory Usage ---
python_list = list(range(num_elements))
# sys.getsizeof() reports the size of the list structure itself,
# which holds references (pointers) to the actual Python integer objects.
# It does NOT include the memory taken by the individual integer objects.
list_structure_size_bytes = sys.getsizeof(python_list)

print(f"\nPython List (structure size for {num_elements} elements): {list_structure_size_bytes} bytes")
print(f"  (Each element in a Python list is a separate Python object, adding significant overhead.)")

# --- NumPy Array Memory Usage ---
# NumPy arrays store elements contiguously and efficiently.
# .nbytes gives the total bytes consumed by the array's data buffer itself.
numpy_array = np.arange(num_elements, dtype=np.int64) # Using int64 for a typical numerical array
numpy_array_data_size_bytes = numpy_array.nbytes

print(f"\nNumPy Array (data size for {num_elements} int64 elements): {numpy_array_data_size_bytes} bytes")
print(f"  (NumPy stores elements directly in a contiguous block of memory, which is memory efficient.)")

Comparing memory usage for 100000 elements:

Python List (structure size for 100000 elements): 800056 bytes
  (Each element in a Python list is a separate Python object, adding significant overhead.)

NumPy Array (data size for 100000 int64 elements): 800000 bytes
  (NumPy stores elements directly in a contiguous block of memory, which is memory efficient.)


In [4]:
import time

# Define a large number of elements for comparison
size = 10**6

# --- Python List Operations ---
print(f"Performing operations on Python lists with {size} elements...")

# Creating a Python list
start_time = time.time()
py_list = list(range(size))
end_time = time.time()
print(f"Time taken to create Python list: {end_time - start_time:.6f} seconds")

# Element-wise operation (e.g., squaring each element)
start_time = time.time()
py_list_squared = [x**2 for x in py_list]
end_time = time.time()
print(f"Time taken for element-wise squaring (Python list): {end_time - start_time:.6f} seconds")

# --- NumPy Array Operations ---
print(f"\nPerforming operations on NumPy arrays with {size} elements...")

# Creating a NumPy array from a Python list
start_time = time.time()
np_array = np.array(range(size))
end_time = time.time()
print(f"Time taken to create NumPy array: {end_time - start_time:.6f} seconds")

# Element-wise operation (e.g., squaring each element)
start_time = time.time()
np_array_squared = np_array**2
end_time = time.time()
print(f"Time taken for element-wise squaring (NumPy array): {end_time - start_time:.6f} seconds")

Performing operations on Python lists with 1000000 elements...
Time taken to create Python list: 0.038388 seconds
Time taken for element-wise squaring (Python list): 0.075902 seconds

Performing operations on NumPy arrays with 1000000 elements...
Time taken to create NumPy array: 0.086419 seconds
Time taken for element-wise squaring (NumPy array): 0.001451 seconds


In [6]:
list = [1,2,3,4,5]

In [7]:
type(list)

list

In [8]:
arr1 = np.array(list)

In [9]:
print(arr1)

[1 2 3 4 5]


In [10]:
type(arr1)

numpy.ndarray

In [11]:
arr1.ndim

1

In [12]:
arr1.dtype

dtype('int64')

In [14]:
arr1.dtype.name

'int64'

In [16]:
arr1.size

5

In [17]:
arr1.shape

(5,)

In [18]:
arr1.nbytes

40

In [19]:
tupple = (1,2,3,4,5)

In [20]:
type(tupple)

tuple

In [23]:
tuple2 = (1,)

In [24]:
type(tuple2)

tuple

In [25]:
arr2 = np.array(tuple)

In [26]:
print(arr2)

<class 'tuple'>


In [27]:
arr2.ndim

0

In [29]:
arr2.dtype

dtype('O')

In [28]:
arr2.shape

()

In [30]:
# Create a 2-dimensional array (matrix) using a Python list
# This is a list of lists, where each inner list represents a row.
two_d_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

print("2D List:")
print(two_d_list)

print("\nAccessing elements:")
print(f"Element at row 0, column 1: {two_d_list[0][1]}") # Accesses '2'
print(f"Element at row 2, column 0: {two_d_list[2][0]}") # Accesses '7'

2D List:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Accessing elements:
Element at row 0, column 1: 2
Element at row 2, column 0: 7


In [32]:
lst = [[1,2],[3,4]]

In [43]:
matrix = np.array(lst)

In [44]:
print(matrix)

[[1 2]
 [3 4]]


In [45]:
matrix.ndim

2

In [46]:
matrix.shape

(2, 2)

In [47]:
matrix.size

4

In [48]:
matrix.nbytes

32

In [54]:
matrix2 = matrix.flatten()

In [53]:
matrix.ravel()

array([1, 2, 3, 4])

In [55]:
matrix2.ndim

1

In [56]:
arr3 = np.array([1,2,3,4])

In [57]:
print(arr3)

[1 2 3 4]


In [58]:
arr4 = np.array([[1,2],[3,4]])

In [59]:
print(arr4)

[[1 2]
 [3 4]]


In [60]:
arr5 = np.matrix([[1,2],[3,4],[5,6]])

In [61]:
print(arr5)

[[1 2]
 [3 4]
 [5 6]]


In [64]:
# Create a 1D NumPy array with numbers from 1 to 100
# np.arange(start, stop) generates numbers from 'start' up to (but not including) 'stop'.
# So, to get 1 to 100, we need to set stop to 101.
array_1_to_100 = np.arange(1, 101)

print(array_1_to_100)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [65]:
arr6 = np.arange(1,100)

In [66]:
print(arr6)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [67]:
# Create a 1D NumPy array with multiples of 9 between 1 and 100
# np.arange(start, stop, step) generates numbers starting from 'start',
# up to (but not including) 'stop', with an increment of 'step'.
# So, to get multiples of 9, we start at 9 and increment by 9.
multiples_of_9 = np.arange(9, 100, 9)

print(multiples_of_9)

[ 9 18 27 36 45 54 63 72 81 90 99]


In [68]:
arr7 = np.arange(0,100,2)

In [69]:
print(arr7)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [70]:
matrix3 = np.arange(0,10)

In [71]:
print(matrix3)

[0 1 2 3 4 5 6 7 8 9]


In [72]:
matrix3.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
A = np.zeros((3,3), dtype = 'int')

In [79]:
A.dtype.name

'int64'

In [82]:
B = np.ones((3,3),dtype ='int')

In [83]:
B.dtype.name

'int64'

In [85]:
C = np.full((3,3),2)

In [86]:
print(C)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [87]:
D = np.full((10,10),4)

In [88]:
print(D)

[[4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4 4 4 4]]


In [92]:
E = np.eye(3)

In [93]:
print(E)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [94]:
E = np.eye((3),dtype='int')

In [95]:
print(E)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [96]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [104]:
import random

In [105]:
x = np.random.random((3,3))
print(x)

[[0.70828997 0.2927747  0.29762079]
 [0.58939766 0.92822954 0.78225048]
 [0.78034941 0.18698852 0.51304467]]


In [106]:
arr1.max()

np.int64(5)

In [107]:
arr1.min()

np.int64(1)